### ISSUE TITLE
0.2.0 agent: Improving fetch_custom_resource to use reflector

### ISSUE THREAD

**Issue by gthao313** [bottlerocket-os/bottlerocket-update-operator#100]
We should avoid polling etcd to get bottlerocket node metadata. Instead of, it's better to use [reflector](https://docs.rs/kube/0.18.0/kube/api/struct.Reflector.html) to watch and cache event.

**Comment by cbgbt** [comment]
We should see if we can also use a `reflector` to improve fetching the `Node` object associated with the node, in `get_node_selector()`.
