### ISSUE TITLE
0.2.0: Do away with crate-wide error modules

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket-update-operator#121]
Error submodules are preferred for error types, and it is preferable to create multiple error classifications rather than bubbling all errors up to a single error type.

**Comment by cbgbt** [comment]
Might be worth dividing this up into tasks for agent/apiserver/controller/etc to make it more tractable.

**Comment by gthao313** [comment]
We have `apiserver` and `model` left.
