### ISSUE TITLE
0.2.0 Make controller a k8s service and provide proper prometheus config

### ISSUE THREAD

**Issue by somnusfish** [bottlerocket-os/bottlerocket-update-operator#133]
**Image I'm using:**

**Issue or Feature Request:**
Provide proper configs that brupop can easily run prometheus server and virtualize the metrics for controller.

**Comment by tjs-intel** [comment]
~The referenced PR provides a prometheus configuration which scrapes on port 9090 (the default for prometheus). The brupop api server is running on port 8080, so I do not think that the provided prometheus configuration (or even the default one) is sufficient for scraping brupop metrics.~

Sorry I was not understanding how scraping metrics works. I needed to add the following annotations to the controller deployment and apiserver deployment:
```
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
```

These annotations could be added to https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/yamlgen/deploy/bottlerocket-update-operator.yaml

**Comment by somnusfish** [comment]
Thanks for reaching out.

Controller metrics are scraped via [kubernetes_sd_configs](https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/yamlgen/telemetry/prometheus-resources.yaml#L63-L65) in our example config.

The part generate controller metrics was [deployed as a service by default](https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/yamlgen/deploy/bottlerocket-update-operator.yaml#L491-L506) so `kubernetes_sd_configs` could fetch it.

**Comment by tjs-intel** [comment]
Thank you for explaining! Do you know what the benefits of using `kubernetes_sd_config` is? Should I avoid adding the annotation to my controller deployment?

**Comment by somnusfish** [comment]
From my understand
```
      - job_name: "kubernetes-service-endpoints"
        kubernetes_sd_configs:
          - role: endpoints
```
fetches all prometheus metrics behind a service without any specific configuration.

I don't see any issue using the annotation you mentioned. However you would like to scrape metrics should be decided by your use case. But our yaml generator don't put those annotation by default. We might want to add that annotation if that's the common way how Promethus works with Kubernetes.

**Comment by somnusfish** [comment]
I have created an [issue](https://github.com/bottlerocket-os/bottlerocket-update-operator/issues/159) to track whether we want to make those annotation by default or not.

**Comment by tjs-intel** [comment]
I think it makes sense to apply the annotations to the controller service so that it will be picked up by the default prometheus configuration

**Comment by cbgbt** [comment]
After chatting with @somnusfish I think we can close this in favor of #159
