### ISSUE TITLE
Idea: transform intent into runnable behavior

### ISSUE THREAD

**Issue by jahkeup** [bottlerocket-os/bottlerocket-update-operator#15]
Yeah, I think this is the best place to start improvements (alongside other coordination improvements). I really liked the idea you proposed of using Behavior Trees and really would like to see what an inspired implementation looks like. I think some hybrid that produced predefined Actions (with concrete types behind them) would be slick and enable some testing of responses other than of the subsequent mutations of the annotations.

I don't think we'll be able to get away from the 3 variables - for many reasons as we discussed: we need to be able to observe pending/active actions taken (for ACKs and monitoring) and also to be able to discern between current (or reached state) and the desired next state. We may be able to collapse these into 2 annotations thought that may severely overload them, I'm open to the discussion and changing of these annotations. I'm interested to hear some alternative ideas we could put in place here.

_Originally posted by @jahkeup in https://github.com/amazonlinux/PRIVATE-thar/pull/239_

**Comment by cbgbt** [comment]
I think we've ended up solving some of the problems discussed here by using the BottlerocketShadow custom resources in [0.2.0](https://github.com/bottlerocket-os/bottlerocket-update-operator/releases/tag/v0.2.0) release.

Intents are defined via the `spec` of the Shadow, and the current state is encoded in the `status`. We model node-level changes by thinking of the brupop agent as a single-node control loop which drives the `status` towards the `spec`, and the cluster level controller as modifying `specs` to drive the overarching cluster to the desired state.

For more details, check out the [design](https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/design/DESIGN.md) doc.
