### ISSUE TITLE
Permission error pulling from regional registry

### ISSUE THREAD

**Issue by tjs-intel** [bottlerocket-os/bottlerocket-update-operator#157]
I'm trying to pull the following image:
`328549459982.dkr.ecr.us-west-2.amazonaws.com/bottlerocket/bottlerocket-update-operator:v0.2.0`

I get the following error:
```
Error response from daemon: Head "https://328549459982.dkr.ecr.us-west-2.amazonaws.com/v2/bottlerocket/bottlerocket-update-operator/manifests/v0.2.0": no basic auth credentials
```

If I try logging in to that registry:
`aws ecr get-login --registry-id 328549459982 --region us-west-2 --no-include-email | sh`

Then when I pull I get this error:
```
Error response from daemon: pull access denied for 328549459982.dkr.ecr.us-west-2.amazonaws.com/bottlerocket/bottlerocket-update-operator, repository does not exist or may require 'docker login': denied: User: arn:aws:iam::***:user/taylorjs is not authorized to perform: ecr:BatchGetImage on resource: arn:aws:ecr:us-west-2:328549459982:repository/bottlerocket/bottlerocket-update-operator because no resource-based policy allows the ecr:BatchGetImage action
```

Am I doing something wrong?

**Comment by gthao313** [comment]
@tjs-intel Thanks for raising this issue. The Image URI you were using was incorrect. It should be 

```
328549459982.dkr.ecr.us-west-2.amazonaws.com/bottlerocket-update-operator:v0.2.0
```
Can you share with us where did you get the image URI from? It can help us to fix it if you find it in Bottlerocket Update Operator document.

Hope that can solve your question. If you still can't pull the image from regional registry, please feel free to let us help you. Thanks.

**Comment by tjs-intel** [comment]
I followed the instructions here https://github.com/bottlerocket-os/bottlerocket-update-operator#image-region

I replaced `public.ecr.aws` in `public.ecr.aws/bottlerocket/bottlerocket-update-operator:v0.2.0` with the appropriate regional registry.

I can pull the image URI you shared, thank you.

**Comment by gthao313** [comment]
We'll improve image-region part on README. Thanks.
