### ISSUE TITLE
Field from CRD manifest gets removed after applying the manifest

### ISSUE THREAD

**Issue by michalschott** [bottlerocket-os/bottlerocket-update-operator#205]
operator version 0.2.1 / develop

```
➜  k version --short
Client Version: v1.22.9
Server Version: v1.22.6-eks-14c7a48
```

[This](https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/yamlgen/deploy/bottlerocket-update-operator.yaml#L10) extra field in CRD definition gets removed after applying the manifest, thus tools like ArgoCD/FluxCD are constantly running tasks to update the in-cluster crd manifest.

**Comment by somnusfish** [comment]
Hi @michalschott,

Thanks for reaching out. Would you mind elaborate more on the issue you just reported?

> operator version 0.2.1 / develop

The version that you mentioned here are actually two version, 0.2.1 and develop. which version did you use and what manifest did you apply? Note that the `bottlerocket-update-operator.yaml` for 0.2.1 is different than the one in develop.

And what is the error that you are facing?

Thanks

**Comment by michalschott** [comment]
Apologies to not being clear enough at the beginning.

I've used [this manifest](https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/v0.2.1/yamlgen/deploy/bottlerocket-update-operator.yaml#L10), but also [this one](https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/yamlgen/deploy/bottlerocket-update-operator.yaml#L10). Both of them have field `.spec.names.categories[]` defined which is being removed by kubernetes (in my case EKS 1.22) once manifest is applied. This results in a gap / difference between defined and in-live manifest, which causes tools like ArgoCD / FluxCD to constantly reapply defined manifests.

Solution would be to drop mentioned field from auto-generated manifest.

**Comment by somnusfish** [comment]
The manifest get updated in our latest release 0.2.2, closing this issue for now and please feel free to reopen/create a new issue if you have further concerns.
