### ISSUE TITLE
How many cpu/memory does brupop use

### ISSUE THREAD

**Issue by gthao313** [bottlerocket-os/bottlerocket-update-operator#240]
Asked by customer. Need investigate on how many cpu/memory resources does brupop use.

**Comment by bcressey** [comment]
A nice end state here would be to add CPU and memory limits to all the pods involved.

**Comment by MiLk** [comment]
In a 10 nodes cluster, over the past 24h, when 2 nodes have been updated to the latest version, I have the following data to share.

Overall CPU and memory usage for apiserver and controller:
![image](https://user-images.githubusercontent.com/29782/197082846-0a57d254-07fd-43e3-ad16-7fc2783f6dba.png)
CPU is < 2.5 mcores
Memory usage is < 8MB

![image](https://user-images.githubusercontent.com/29782/197082990-d5bbda3b-6190-4817-9141-f205b3227d72.png)
![image](https://user-images.githubusercontent.com/29782/197083040-44005a25-c17a-4fe1-a1c0-04b41a41c809.png)

For the agents, we can also observe a memory usage < 8MB
![image](https://user-images.githubusercontent.com/29782/197083257-ff0c067c-12f8-47a7-b9f1-e700eac83d85.png)
CPU usage stays < 5mcores
![image](https://user-images.githubusercontent.com/29782/197083431-726f1256-f90b-49a9-b438-94cfdf362b4c.png)

The agents of the nodes which have been updated
![image](https://user-images.githubusercontent.com/29782/197083738-87f50ee2-c2c0-4126-9d76-895d5f541e13.png)
![image](https://user-images.githubusercontent.com/29782/197083802-366a6630-aa16-4bd4-bd8b-3b20f32c5537.png)

**Comment by jpmcb** [comment]
Ran a similar experiment with a 3 node cluster updating from 1.9.0 to 1.10.1 using the [kubernetes metrics server](https://github.com/kubernetes-sigs/metrics-server) and [the kubernetes dashboard](https://github.com/kubernetes/dashboard) (for simple metrics gathering)

![Screen Shot 2022-10-27 at 1 22 13 PM](https://user-images.githubusercontent.com/23109390/198380042-7708dd56-1a61-4d66-bf96-c9c9a57b08d1.png)

Over the course of the update, I got similar results:

#### CPU

- Controller peaked at and idles at about ~1.00 cores
- Api servers peak at and idle at roughly ~2.00 cores 
- Agents peak at and idle at ~1.00 cores

#### Memory

- Controller peaked at and idles around ~2.75-3 Mi
- Api servers each idle around ~3.5 Mi
- Agents peaked at ~8 and idle around 7 Mi
