### ISSUE TITLE
Consider combining license scan and build Dockerfiles

### ISSUE THREAD

**Issue by jahkeup** [bottlerocket-os/bottlerocket-update-operator#26]
> I'd like to see the separation in Dockerfiles go away later. Coordinating two separate image builds by way of a Makefile used to be a requirement prior to the advent of multi-stage Dockerfiles, but at this point multi-stage Dockerfiles are a more clear representation of the dependencies between build steps of container images.  The fact that we're having this discussion and the need for extra documentation is an artifact of this being a non-standard pattern; I see this as a barrier to entry for new contributors who will need to read two Dockerfiles *and* a Makefile to understand how the image is built.

_Originally posted by @samuelkarp in https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/6_

**Comment by cbgbt** [comment]
With version [0.2.0](https://github.com/bottlerocket-os/bottlerocket-update-operator/releases/tag/v0.2.0) we have merged the license generation into the primary Dockerfile.
