### ISSUE TITLE
GitHub action to check for changes to `yamlgen/deploy/...`

### ISSUE THREAD

**Issue by jpmcb** [bottlerocket-os/bottlerocket-update-operator#314]
### Issue or Feature Request:

There's been a few dependency upgrades that have changed the deployment yaml from under us. We should implement a GitHub action (probably just after the build step) to ensure the repo is "clean" so we aren't accidentally changing anything in the generated yamls.

**Comment by webern** [comment]
This is what we do over here https://github.com/bottlerocket-os/bottlerocket-test-system/blob/2a999cf11e300986983702d3174b5cfdf0c3c3e7/.github/workflows/build.yaml#L25
