### ISSUE TITLE
Agent log line "API Server busy" seems like an error

### ISSUE THREAD

**Issue by James-Quigley** [bottlerocket-os/bottlerocket-update-operator#433]
**Image I'm using:**
1.0.0

**Issue or Feature Request:**
The brupop agent appears to poll to see if there is an update available for the node, and if there is no update available, logs

> API server busy, retrying later

IMO The server being busy makes it seem like requests are failing or that there is some kind of underlying issue, as opposed to being on the latest OS.

**Comment by igorgolm** [comment]
It could be also great if apiserver could have configured log levels, like DEBUG, INFO, WARN etc...seems like currently it doesn't

**Comment by gthao313** [comment]
@James-Quigley @igorgolm  Thanks for raising this issue! We will take a look at it. : )

**Comment by cbgbt** [comment]
The original error message mentioned has been resolved as part of https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/496.

I've opened https://github.com/bottlerocket-os/bottlerocket-update-operator/issues/509 to track exposing the log-level as a configuration option. I'll close this issue in favor of those.

Thanks!
