### ISSUE TITLE
Improve region-specific deployment story

### ISSUE THREAD

**Issue by jahkeup** [bottlerocket-os/bottlerocket-update-operator#44]
**Issue or Feature Request:**

#43 adds the list of image repositories by region. The usage of these regional repositories should be improved for users. One way could be to eliminate the need to directly edit deployment data. There are methods to do this using the community's accepted tooling (e.g. helm charts). However, some fact finding and team deliberation is needed before committing to such tools.

**Comment by samuelkarp** [comment]
Now that the [Amazon ECR public gallery](https://gallery.ecr.aws/) is available, we should publish the update operator there.
