### ISSUE TITLE
Incorrect Prometheus metric values

### ISSUE THREAD

**Issue by dchoy** [bottlerocket-os/bottlerocket-update-operator#441]
**Image I'm using:**
1.1.0

**Issue:**
Scraped Prometheus metrics don't seem to accurately reflect the existing state of all the nodes. It seems like the gauges store old historical data. For example, if a node is updated from Bottlerocket 1.13.0 to 1.13.2, the `brupop_hosts_version` gauge will have a value of the following, reflecting both the initial and final state. This is assuming there is only one node. A restart of the Deployment sets the gauges to the correct/expected values.

```
# HELP brupop_hosts_version Brupop host's bottlerocket version
# TYPE brupop_hosts_version gauge
brupop_hosts_version{bottlerocket_version="1.13.0",service_name="unknown_service"} 1
brupop_hosts_version{bottlerocket_version="1.13.2",service_name="unknown_service"} 1
```

Expected:

```
# HELP brupop_hosts_version Brupop host's bottlerocket version
# TYPE brupop_hosts_version gauge
brupop_hosts_version{bottlerocket_version="1.13.2",service_name="unknown_service"} 1
```

I believe the issue has been there from the initial implementation as the initial comment in the discussion for pull request 132 (https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/132) seems to illustrate the same issue (5 node cluster, but the sum of the values from brupop_hosts_version is 6).

A similar issue seems to exist for the `brupop_hosts_state` gauge as well.

If it was a counter, this could make sense, but a gauge should represent the current value for the metric (for each set of labels specified).

**Comment by etungsten** [comment]
Thanks for bringing this issue to our attention. We'll take a closer look at this.
