### ISSUE TITLE
Operator does not seem to handle reverts in the upstream

### ISSUE THREAD

**Issue by hajdukda** [bottlerocket-os/bottlerocket-update-operator#452]
**Image I'm using:**
public.ecr.aws/bottlerocket/bottlerocket-update-operator:v1.0.0

**Issue or Feature Request:**
Recently there was a revert to the runc version on the bottlerocket-os. I've checked the version of runc we run after the release was available and operator performed the update.

We were still running version 1.1.6 when the revert changed it back to 1.1.5. It seems the update does not cover reverts in the upstream.
Please investigate.

**Comment by cbgbt** [comment]
Hi @hajdukda.

The revert to runc 1.1.5 occurred via a fast-forward from the perspective of Bottlerocket, from Bottlerocket 1.13.4 to [1.13.5](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.13.5). The update-operator should see this the same as any other update.

My suspicion is that you are still waiting for Bottlerocket's wave schedule to include the nodes in your cluster. Check out the documentation on [update-related settings](https://github.com/bottlerocket-os/bottlerocket#updates-settings) or this section of [the updater docs.](https://github.com/bottlerocket-os/bottlerocket/tree/develop/sources/updater#update-wave)

Basically, nodes self-assign a random integer on firstboot which dictates when they will deem themselves ready to consume updates. The wave schedule typically takes about 1 week to complete.

If you would like to ignore the wave schedule to consume this update, you could modify your instance settings to do so via:

```
apiclient set settings.updates.ignore-waves=true
```

If you check the output of `apiclient update check` before and after performing this on a node, you should see that `available_updates` will change to reflect that the `1.13.5` update is available.

The Bottlerocket update operator will respect any of these settings applied to your host, although I wouldn't recommend keeping `ignore-waves` enabled in the long-term.

If setting `ignore-waves` doesn't solve your problem, please do let us know!

**Comment by hajdukda** [comment]
I've verified before writing this ticket that the nodes were running latest update and
`apiclient update check` returned that we are using the latest version `1.13.5`. The release happened 2 days before creation of this ticket. And we had over that time 2 update windows during which version was updated (but runc not).

I would not create this ticket if the update would be still pending. Revert of runc package did not work.

`runc --version` was still returning 1.1.6. We had to update nodes manually to latest AMI to revert package version.

EKS version is 1.24. kubelet version v1.24.10-eks-08ad9cc.

**Comment by cbgbt** [comment]
Thanks for the additional details. I’ve attempted to reproduce this issue without luck. Here are the steps I took to determine the Bottlerocket and runc versions, as well as to interrogate Brupop to determine which updates were occurring:

Brupop's BottlerocketShadow shows that the node has targeted a new state to perform an update.
```
$ kubectl get brs
NAME                                               STATE   VERSION   TARGET STATE               TARGET VERSION   CRASH COUNT
brs-ip-192-168-2-100.us-west-2.compute.internal    Idle    1.13.4    StagedAndPerformedUpdate   1.13.5           0
```

On the Bottlerocket node, prior to the update. The host is running Bottlerocket 1.13.4
```
[ec2-user@admin]$ sudo sheltie
bash-5.1# cat /etc/os-release 
NAME=Bottlerocket
ID=bottlerocket
VERSION="1.13.4 (aws-k8s-1.24)"
PRETTY_NAME="Bottlerocket OS 1.13.4 (aws-k8s-1.24)"
VARIANT_ID=aws-k8s-1.24
...
```

runc reports version 1.1.6+bottlerocket:
```
bash-5.1# runc --version
runc version 1.1.6+bottlerocket
commit: 0f48801a0e21e3f0bc4e74643ead2a502df4818d
spec: 1.0.2-dev
go: go1.19.6
libseccomp: 2.5.4
```

Then I lost connection as the node rebooted into the new update:
```
bash-5.1# Connection to 18.237.25.90 closed by remote host.
Connection to 18.237.25.90 closed.
```

Back to watching Brupop: we see that the host has rebooted into 1.13.5. Let's check it out:
```
$ kubectl get brs
NAME                                               STATE                VERSION   TARGET STATE       TARGET VERSION   CRASH COUNT
brs-ip-192-168-2-100.us-west-2.compute.internal    RebootedIntoUpdate   1.13.5    MonitoringUpdate   1.13.5           0
```

Indeed, the host is on Bottlerocket 1.13.5 now:
```
$ sudo sheltie
bash-5.1# cat /etc/os-release 
NAME=Bottlerocket
ID=bottlerocket
VERSION="1.13.5 (aws-k8s-1.24)"
PRETTY_NAME="Bottlerocket OS 1.13.5 (aws-k8s-1.24)"
VARIANT_ID=aws-k8s-1.24
...
```

And runc reports 1.1.5+bottlerocket:
```
bash-5.1# runc --version
runc version 1.1.5+bottlerocket
commit: f19387a6bec4944c770f7668ab51c4348d9c2f38
spec: 1.0.2-dev
go: go1.19.6
libseccomp: 2.5.4
```

@hajdukda, Could you possibly run the same commands and provide the output? Specifically running `sudo sheltie` to enter the host namespace, then checking the `VERSION` in `/etc/os-release` as well as `runc --version`, then finally the state of the bottlerocketshadow in kubernetes.

**Comment by cbgbt** [comment]
We haven't been able to reproduce this issue. Without further details, we will close it for now. Please feel free to re-open it if you have more information. Thanks!
