### ISSUE TITLE
Unable to operate on BottlerocketShadow

### ISSUE THREAD

**Issue by Bakrog** [bottlerocket-os/bottlerocket-update-operator#459]
**Image I'm using:**
public.ecr.aws/bottlerocket/bottlerocket-update-operator:v1.1.0

**Issue or Feature Request:**
I followed the readme installation but all my agents are showing the following error message:
```shell
  2023-05-30T10:34:05.620481Z ERROR agent::agentclient: error: Unable to operate on BottlerocketShadow: 'Unable to gather system chosen update metadata: 'Failed to refresh updates or update action performed out of band''
    at agent/src/agentclient.rs:183
    in agent::agentclient::shadow_status_with_refreshed_system_matadata with shadow_error_info: ShadowErrorInfo { crash_count: 0, state_transition_failure_timestamp: None }
    in agent::agentclient::initialize_metadata_shadow
    in agent::agentclient::initialize_shadow_if_not_initialized
    in agent::agentclient::run

  2023-05-30T10:34:05.620519Z ERROR agent::agentclient: error: Unable to operate on BottlerocketShadow: 'Unable to gather system chosen update metadata: 'Failed to refresh updates or update action performed out of band''
    at agent/src/agentclient.rs:245
    in agent::agentclient::initialize_metadata_shadow
    in agent::agentclient::initialize_shadow_if_not_initialized
    in agent::agentclient::run

  2023-05-30T10:34:05.620529Z  WARN agent::agentclient: An error occurred when try to initialize BottlerocketShadow. Restarting event loop.
    at agent/src/agentclient.rs:504
    in agent::agentclient::run


```

What can be wrong?

**Comment by jpmcb** [comment]
Hi @Bakrog - thanks for raising this issue.

This error gets raised when the agents attempt to call `apiclient raw -u /updates/status` and for some reason, that fails. This could be for a few reasons (like network issues, using a custom tuf repo with the wrong update url, etc.) 

A few things to check:
- Can you ssh / ssm onto the bottlerocket node and manually run `apiclient update check` and see if you get errors?
- Have you made any settings changes to the bottlerocket node (especially in the settings.updates area)?
- What messages/errors are you getting in the controller? The agents are what actually work on each individual bottlerocket node and the controller may have some more helpful messages

**Comment by Bakrog** [comment]
Hi, I think it was a problem with my worker nodes on version 1.22.
I upgrade my cluster to version 1.25 and now everything works fine.
But answering your points:
* I saw same error from it
* I do have some changes but I don't think they are related, this is my template: 
```
[settings.boot]
reboot-to-reconcile = true

[settings.kernel]
lockdown = "integrity"

[settings.kernel.sysctl]
"net.ipv4.conf.all.rp_filter" = "0"
"net.ipv4.conf.eth0.rp_filter" = "0"

[settings.host-containers.admin]
enabled = false

[settings.kubernetes]
api-server = "{{ cluster_api }}"
cluster-certificate = "{{ cluster_certificate }}"
cluster-name = "{{ cluster_name }}"

[settings.kubernetes.node-labels]
{{ node_labels }}

[settings.kubernetes.node-taints]
{{ node_taints }}
```
* There was no error on the controllers.

Thank you very much for the fast message, I'll close with this comment as it seems upgrading solve it.
