### ISSUE TITLE
Add getting started guide

### ISSUE THREAD

**Issue by jahkeup** [bottlerocket-os/bottlerocket-update-operator#46]
**Issue or Feature Request:**

The repository should include directed, "getting started" documentation that walks through standing up the update operator in a cluster. This documentation should also provide pointers to some details (such as how the host influences updates and delays) as they're mentioned or relevant in the guide.

**Comment by jahkeup** [comment]
The influence that host settings, update waves, and the deployment of the operator's pods has on the update process is left unclear - these details should be clarified in the guide while walking the user through the setup.

**Comment by arhea** [comment]
It would also be good to call out the major version upgrade process. That wasn't clear when deploying the operator that creating new node groups is the recommend method for upgrading the version of Kubernetes.

**Comment by srgothi92** [comment]
Fixed in [PR-62](https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/62)
