### ISSUE TITLE
Chart information is no up to date

### ISSUE THREAD

**Issue by evgeni-roif-gong** [bottlerocket-os/bottlerocket-update-operator#469]
Trying to deploy using the helm chart is not working.
```
➜  test-brupop git:(main) ✗ helm repo add brupop https://bottlerocket-os.github.io/bottlerocket-update-operator
Error: looks like "https://bottlerocket-os.github.io/bottlerocket-update-operator" is not a valid chart repository or cannot be reached: failed to fetch https://bottlerocket-os.github.io/bottlerocket-update-operator/index.yaml : 404 Not Found
```

In addition, going to the deploy/chart folder looking for the current chart shows the image of 1.0.0 instead of 1.1.0 like the current release.

Is chart based deployment still supported or using the manifest is preferred?

**Comment by stmcginnis** [comment]
Hi @evgeni-roif-gong - helm support is something just being added now. I think the initial support was merged just in the last week or so. There has not been a release since then, but it will be updated when it is ready. Thanks!

**Comment by jpmcb** [comment]
FYI - in the meantime, if you'd like to be _on the cutting edge_, you can clone this repo and install the helm chart manually from the chart templates directly.

```bash
# Get into the directory where you've cloned the repo
$ cd brupop-clone

# Install the bottlerocket shadow CRD from the templates directly
$ helm install brupop-crd deploy/charts/bottlerocket-shadow

# Create the namespace
$ kubectl create namespace brupop-bottlerocket-aws

# Install the operator from the templates directly
$ helm install brupop deploy/charts/bottlerocket-update-operator
```

**Comment by takhat** [comment]
@jpmcb We tried this and still weren't able to deploy the BottleRocket operator. The pod seems to be restarting.
Fyi - we were able to install BottleRocket Shadow and BottleRocket API with above Helm commands but we are getting this below error for BottleRocket operator pod:
```
ERROR controller: controller exited
    at controller/src/main.rs:94 
```
Can you please suggest what is wrong and how to fix it? Thanks for your help!

**Comment by gthao313** [comment]
Hi @takhat @evgeni-roif-gong Sorry for the late response. Currently we have already released new version [1.2.0 ](https://github.com/bottlerocket-os/bottlerocket-update-operator/releases/tag/v1.2.0).  You're able to use helm chart at this new version. Feel free to let me if you have question! thanks for using bottlerocket-update-operator!   : )

**Comment by gthao313** [comment]
the new version with helm chart had been release and Chart information is up to date

**Comment by takhat** [comment]
Thank you @gthao313!
