### ISSUE TITLE
Unable to use Helm charts because they seem to be still a work in progress

### ISSUE THREAD

**Issue by takhat** [bottlerocket-os/bottlerocket-update-operator#471]
Hi,

We followed the steps mentioned in the ReadMe to deploy the BottleRocket operator through Helm Charts but we were unable to deploy it. The container keeps on restarting without any valid error. Can you please confirm if the Helm charts are still work in progress or a new version will be released? When can we expect a new version?

Thanks!

**Comment by etungsten** [comment]
Hi @takhat,

You're correct. The new version has not been released yet. Please refer to this prior issue https://github.com/bottlerocket-os/bottlerocket-update-operator/issues/469. I'll go ahead and close this one.

**Comment by takhat** [comment]
Thank you @etungsten!
