### ISSUE TITLE
Questions regarding update failures and node labeling

### ISSUE THREAD

**Issue by am-cloudservices** [bottlerocket-os/bottlerocket-update-operator#472]
Hi everyone

I am implementing the brupop in future EKS production environment.

All went well and I am currently updating our internal docs. There were a few questions that I couldn't answer regarding the current documentation on Github.

**Labeling the nodes**
We are setting up our cluster with Terraform and I add the label **bottlerocket.aws/updater-interface-version=2.0.0** to the EKS launch template. 

- What is the relationship between the brupop and the api-interface-version? 
- Will a change to this api-interface-version affect the operation of brupop?
- Do I have to change the label with each new brupop version?

**Behaviour in error case**
According to https://aws.amazon.com/bottlerocket/faqs/ the Bottlerocket OS will be rolled back if the update fails.

> The integration component enables the orchestrator to initiate reboots, rollback updates, and replace containers in a minimally disruptive manner for rolling upgrades.

- Is this also true for brupop? If an update fails, will the node be rolled back to the previous working OS?

I'm looking forward to your answers and would be happy to create a pull request to add your answers to the documentation.
Kind regards

**Image I'm using:**
v1.1.0

**Comment by gthao313** [comment]
Hi @am-cloudservices thanks for opening this issue. We have more info [here](bottlerocket.aws/updater-interface-version=2.0.0) in case you didn't see it! : )

>What is the relationship between the brupop and the api-interface-version?

`bottlerocket.aws/updater-interface-version=2.0.0` is a node-label, which uses allow brupop to schedule the update on it. If you don't label the node, brupop will not be allowed to schedule any pods or jobs on the node. 

>Will a change to this api-interface-version affect the operation of brupop?

May I ask what do you mean a "change" here? 

 >Do I have to change the label with each new brupop version?
 
 Once you label a node and never un-label it, it will not affect new brupop version. whatever the brupop version, brupop always try to schedule the jobs on the labeled nodes.
 
>Is this also true for brupop? If an update fails, will the node be rolled back to the previous working OS?

yes, it's true. If the update fails on the process, brupop will stop the update and bring it back to the previous version. Meanwhile, brupop will try to update the node later.

**Comment by am-cloudservices** [comment]
Hi @gthao313 thank you for your answer. Unfortunately I wasn't able to open (or find) the infos you provided with the link. It lead to "Not Found"

> May I ask what do you mean a "change" here?

My question should have been: Will the version of this label change? For example from 2.0.0 to 2.0.1?

Thank you very much for answering the questions, this will help us to roll out the brupop on our clusters.

**Comment by gthao313** [comment]
Sorry about that! here is the link https://github.com/bottlerocket-os/bottlerocket-update-operator#label-nodes.

>My question should have been: Will the version of this label change? For example from 2.0.0 to 2.0.1?

No, we usually not change the label. You can treat it as a node-label and the version doesn't matter.If we change it later, I think users just need re-label the nodes to the new label.

**Comment by am-cloudservices** [comment]
Hi @gthao313 Thank you very much for the provided information.

I am now confident to go to production state with the brupop. As I have already opened an issue, I have a last question: Is there a release plan? We are looking forward to the cron based maintenance window, as this would be a great feature.

Thank you again for your time and patience.

**Comment by gthao313** [comment]
@am-cloudservices Yes, next version will introduce cron scheduler and helm chart! The release is on our plan and we will release next version soon!

**Comment by am-cloudservices** [comment]
@gthao313 Thank you very much. Keep up the good work!
