### ISSUE TITLE
Log Output Formating: --no-pretty-mode

### ISSUE THREAD

**Issue by maxres-ch** [bottlerocket-os/bottlerocket-update-operator#493]
**Image I'm using:**

public.ecr.aws/bottlerocket/bottlerocket-update-operator:v1.1.0
**Issue or Feature Request:**
Feature Request:

As a user of this controller I would like to have log output that isn't "pretty" because it interferes with my logging and observability  tools/SaaS e.g. datadog. 

Right now the logs when pulled from `kubectl log XYZ"` are nice but in tools like datadog they are less tolerable. 

I would like to be able to disable pretty out mode for plain text or json.

example:
<img width="1172" alt="Screen Shot 2023-07-27 at 12 34 48 PM" src="https://github.com/bottlerocket-os/bottlerocket-update-operator/assets/93956521/7aae7113-4854-4c34-a7bf-1374721b03e0">

**Comment by gthao313** [comment]
@maxres-ch Thanks for opening the issue! We will backlog the issue and improve logging system on brupop! 

Meanwhile, we recommend you to use bottlerocket-update-operator:v1.2.0 which is our latest version. Thanks! : )

**Comment by cbgbt** [comment]
I've opened #503 which makes this configurable via a helm values file (or modifying environment variables in the yaml definition of the service).

**Comment by maxres-ch** [comment]
Awesome @cbgbt . Thanks for the fast turn around.
