### ISSUE TITLE
brupop agent is not installing using Helm Charts

### ISSUE THREAD

**Issue by takhat** [bottlerocket-os/bottlerocket-update-operator#495]
Hello,

We are having issues deploying the helm charts that were recently released. The `brupop-agent` is not getting installed and no daemon sets agent pods are being created. Since the `brupop-agent` is not getting installed, the update-operator is not updating the node at the scheduled time as expected. The controller logs show the following error:
```
INFO controller::controller: Unable to find associated bottlerocketshadow, skip sort.
```
Do you know if this is a known issue? Thanks!

**Comment by cbgbt** [comment]
Hi, thanks for opening this issue.

Just to double check, have you followed this portion of the [installation instructions](https://github.com/bottlerocket-os/bottlerocket-update-operator#installation)?

> Label nodes with bottlerocket.aws/updater-interface-version=2.0.0 to indicate they should be automatically updated. Only bottlerocket nodes with this label will be updated. For more information on labeling, refer to the [Label nodes section of this readme.](https://github.com/bottlerocket-os/bottlerocket-update-operator#label-nodes)

The agent is only deployed to nodes which have been labeled with `bottlerocket.aws/updater-interface-version=2.0.0`.

**Comment by cbgbt** [comment]
In #506 we updated the controller to emit this message if no Shadow objects were found, which should help debug situations like I mentioned in my previous comment:

> Nothing to do: The bottlerocket-update-operator is not aware of any BottlerocketShadow objects. Is the bottlerocket-shadow CRD installed? Are nodes labelled so that the agent is deployed to them? See the project's README for more information.

**Comment by takhat** [comment]
Thanks for your reply @cbgbt! Yes we had labeled the nodes correctly. We found out that the issue was that certain taints preventing the brupop agent pod from getting created. We allowed taint tolerations and were able to fix the issue. Thanks!

**Comment by cbgbt** [comment]
@takhat, thanks for following up, and glad you found the solution!

In the next planned Brupop release, we'll be adding a mechanism for setting up tolerations via Helm (https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/513). Hopefully this will help with managing the installation!
