### ISSUE TITLE
Templating for tolerations / nodeselector throughout the helm chart

### ISSUE THREAD

**Issue by hofalk** [bottlerocket-os/bottlerocket-update-operator#500]
Image I'm using: 1.2.0

Issue or Feature Request: Feature Request

We are making use of taints and tolerations to group different node-roles inside our cluster. This prevents brupop to schedule updates for any tainted nodes, as it is excluded from running an agent there.

Also, it would be nice to be able to control the scheduling of the central components (apiserver & controller) to specific nodes by exposing `nodeSelector` and `pod(Anti)Affinity` throughout the helm chart. This would enable us to group our "infra-relevant" deployments on a seperated group of nodes.

I would gladly create a PR if required, but it comes down to adding a few lines of default helm templating, like

```yaml
# ...
{{- with .Values.tolerations }}
tolerations:
  {{- toYaml . | nindent 8 }}
{{- end }}
# ...
```
for the agent daemonset, api-server and controller deployment. And something like

```yaml
# ...
{{- with .Values.nodeSelector }}
nodeSelector:
  {{- toYaml . | nindent 8 }}
{{- end }}
# ...
```
for api-server and controller deployment.

**Comment by cbgbt** [comment]
Thanks for bringing this up, this is a good suggestion. I'll take a look at implementing this.

**Comment by cbgbt** [comment]
@hofalk we're planning to release this in Brupop 1.3.0, which you can track in https://github.com/bottlerocket-os/bottlerocket-update-operator/issues/508.

I was curious if you wouldn't mind weighing in on the implementation (https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/513). I think your suggested use-case of separating infrastructure pods onto their own hardware is probably the most likely, but I added individualized controls for each component to allow for other bespoke setups.

I probably should have asked before merging 😅, but happy to circle back if you have any suggestions or concerns.

**Comment by hofalk** [comment]
@cbgbt Wow, that was quick! Looks good to me!

Personally I would have nested the values by component, e.g.

```yaml
controller:
  tolerations: []
  nodeSelector: {}
# ...
```
.. but that is obviously just a matter of taste, and I am happy in any case.

Looking forward to the new release and thanks for your work on this!
