### ISSUE TITLE
Use Bottlerocket SDK latest release

### ISSUE THREAD

**Issue by jahkeup** [bottlerocket-os/bottlerocket-update-operator#52]
**Issue or Feature Request:**

The update operator is building with an older SDK, this should be updated to the latest version ([SDK v0.14.0](https://github.com/bottlerocket-os/bottlerocket-sdk/releases/tag/v0.14.0) at time of writing).

This brings in a newer version of Go as well, so the fallback golang image and the GitHub action build should be updated to use [`1.15.4` (in SDK `v0.14.0`)](https://github.com/bottlerocket-os/bottlerocket-sdk/blob/v0.14.0/Dockerfile#L375).

---

- [ ] Bump SDK container image ref
- [ ] Run tests with builds (updated Go toolchain)
- [ ] Reconfigure golang fallback image
- [ ] Reconfigure GitHub Actions build to use matching version

**Comment by cbgbt** [comment]
This is resolved per @gthao313's work in #63
