### ISSUE TITLE
Control plane nodes update

### ISSUE THREAD

**Issue by mlacko64** [bottlerocket-os/bottlerocket-update-operator#521]
Hello,
I installed latest operator version on my cluster consisting on 3 control planes and 2 worker nodes.
But I see agents running on worker nodes only. And only worker nodes were updated.

So my question is - Is automatic update of control planed nodes supported? Can I enable it for example with agent tolerations or something like that? Or should be just worker nodes updated this way?

Thank you very much for your reply

**Comment by stmcginnis** [comment]
Hi @mlacko64 - I believe all nodes should be able to be updated, but let me double check that. In the meantime, can you check if your control plane nodes have the label `bottlerocket.aws/updater-interface-version=2.0.0`?

You can either do something like:

```bash
kubectl get nodes -l 'bottlerocket.aws/updater-interface-version=2.0.0'
```

Or `kubectl describe` one of your control-plane nodes and check under the "Labels" section.

If the label is not present, then brupop will not consider that node for upgrading. You can apply the label by doing:

```bash
kubectl label node $NODE bottlerocket.aws/updater-interface-version=2.0.0
```

**Comment by cbgbt** [comment]
For what it's worth:
* if the control plane nodes have a taint, you may need to add tolerations to the agent's daemonset. We're adding support for doing this via Helm in Brupop 1.3.0, which you can track in #508
* brupop respects PodDisruptionBudgets when draining nodes to be updated, which may be helpful if the control plane has those configured

I'd still see if @stmcginnis has any further guidance, I'm not sure what other roadblocks are present for control plane nodes.

**Comment by mlacko64** [comment]
Hello,
thanks for your replies. Actually I installed my Bottlerocket cluster as an EKS-Anywhere cluster, which added this taint on control plane nodes:
```
Taints:             node-role.kubernetes.io/control-plane:NoSchedule
```

When I added this toleration to `daemonset.apps/brupop-agent` , agents were started also on control plane nodes:
```
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
```

Similarly I was able to relocate `deployment.apps/brupop-apiserve` to control plane nodes with
```
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
```
and
```
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
```

I updated daemonset and deployment manually (as you mentioned 1.3 was not released yet).
After agents were started on control plane nodes, they  were updated automatically.

Thanks a lot for your support
