### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by springroll12** [bottlerocket-os/bottlerocket-update-operator#53]
**Issue or Feature Request:**

What is the status of this project? Is it still maintained and the recommended way to upgrade bottlerocket? There are a number of significant issues presented in the README and I'm wondering if there is a roadmap or timeline to address them.

In my view, the non-operator mechanisms for upgrading bottlerocket are quite convoluted so it would be nice to see this project get some attention.

If this project is not intended to continue, it would be nice to see efforts contributed to a project like System Upgrade Controller instead: https://github.com/rancher/system-upgrade-controller

**Comment by jhaynes** [comment]
Hi @springroll12 the update operator is definitely still maintained and is the recommended way to automate updates to Bottlerocket nodes in a Kubernetes cluster. Of the gaps in the readme (or open issues) which ones are the most critical for you?

**Comment by bgdnlp** [comment]
I'm not OP, but I'm looking into switching to Bottlerocket and #45 is definitely scary. Not sure how likely it is, but it sounds like it could potentially trigger a cascade that could cause serious disruption. I'd say making sure upgrades and ASGs work nicely together is a requirement for production.

**Comment by jahkeup** [comment]
@bgdnlp if you are able to share a bit more about your use case and infrastructure setup, please do share in #45! Any additional info on how you'd would want an ASG integration to look and work in your environment will help shape the design and would be appreciated.

Thanks for sharing your thoughts here - I look forward to learning more about how the update operator might better fit into your clusters!

**Comment by jhaynes** [comment]
I'm going to close this issue since the initial question is answered about the project's status. However, please don't hesitate to open other issues about specific feature requests or bugs as you find them!
