### ISSUE TITLE
It is unclear whether the operator works

### ISSUE THREAD

**Issue by jRilkef** [bottlerocket-os/bottlerocket-update-operator#538]
**Image I'm using:**
328549459982.dkr.ecr.eu-central-1.amazonaws.com/bottlerocket-update-operator:v1.3.0 (via Helm)

**Issue or Feature Request:**
I can't seem to understand whether the operator functions as intended. See the logs:
<details>
<summary>agent logs</summary>

```
  2023-09-05T09:45:29.558438Z  INFO agent::agentclient: Checking for Bottlerocket updates.
    at agent/src/agentclient.rs:209
    in agent::agentclient::shadow_status_with_refreshed_system_matadata with shadow_error_info: ShadowErrorInfo { crash_count: 0, state_transition_failure_timestamp: None }
    in agent::agentclient::update_status_in_shadow with bottlerocket_shadow: BottlerocketShadow { metadata: ObjectMeta { annotations: None, cluster_name: None, creation_timestamp: Some(Time(2023-08-01T11:01:39Z)), deletion_grace_period_seconds: None, deletion_timestamp: None, finalizers: None, generate_name: None, generation: Some(6), labels: None, managed_fields: Some([ManagedFieldsEntry { api_version: Some("brupop.bottlerocket.aws/v2"), fields_type: Some("FieldsV1"), fields_v1: Some(FieldsV1(Object {"f:metadata": Object {"f:ownerReferences": Object {".": Object {}, "k:{\"uid\":\"ad5d1972-7496-49dd-b461-7514804d38f2\"}": Object {}}}, "f:spec": Object {".": Object {}, "f:state": Object {}}})), manager: Some("unknown"), operation: Some("Update"), subresource: None, time: Some(Time(2023-08-01T11:01:39Z)) }, ManagedFieldsEntry { api_version: Some("brupop.bottlerocket.aws/v2"), fields_type: Some("FieldsV1"), fields_v1: Some(FieldsV1(Object {"f:status": Object {".": Object {}, "f:crash_count": Object {}, "f:current_state": Object {}, "f:current_version": Object {}, "f:target_version": Object {}}})), manager: Some("unknown"), operation: Some("Update"), subresource: Some("status"), time: Some(Time(2023-08-01T11:01:59Z)) }]), name: Some("brs-ip-10-100-2-30.eu-central-1.compute.internal"), namespace: Some("brupop-bottlerocket-aws"), owner_references: Some([OwnerReference { api_version: "v1", block_owner_deletion: None, controller: None, kind: "Node", name: "ip-10-100-2-30.eu-central-1.compute.internal", uid: "ad5d1972-7496-49dd-b461-7514804d38f2" }]), resource_version: Some("328098224"), self_link: None, uid: Some("f03bc730-576f-4149-bcce-b1ef28ec2933") }, spec: BottlerocketShadowSpec { state: Idle, state_transition_timestamp: None, version: None }, status: Some(BottlerocketShadowStatus { current_version: "1.14.3", target_version: "1.14.3", current_state: Idle, crash_count: 0, state_transition_failure_timestamp: None }) }, state: Idle, shadow_error_info: ShadowErrorInfo { crash_count: 0, state_transition_failure_timestamp: None }
    in agent::agentclient::run

  2023-09-05T09:45:30.059064Z  INFO agent::apiclient::api: The lock for the update API is held by another process ...
    at agent/src/apiclient.rs:298
    in agent::apiclient::api::invoke_apiclient with args: ["raw", "-u", "/updates/status"]
    in agent::apiclient::api::get_update_status
    in agent::agentclient::shadow_status_with_refreshed_system_matadata with shadow_error_info: ShadowErrorInfo { crash_count: 0, state_transition_failure_timestamp: None }
    in agent::agentclient::update_status_in_shadow with bottlerocket_shadow: BottlerocketShadow { metadata: ObjectMeta { annotations: None, cluster_name: None, creation_timestamp: Some(Time(2023-08-01T11:01:39Z)), deletion_grace_period_seconds: None, deletion_timestamp: None, finalizers: None, generate_name: None, generation: Some(6), labels: None, managed_fields: Some([ManagedFieldsEntry { api_version: Some("brupop.bottlerocket.aws/v2"), fields_type: Some("FieldsV1"), fields_v1: Some(FieldsV1(Object {"f:metadata": Object {"f:ownerReferences": Object {".": Object {}, "k:{\"uid\":\"ad5d1972-7496-49dd-b461-7514804d38f2\"}": Object {}}}, "f:spec": Object {".": Object {}, "f:state": Object {}}})), manager: Some("unknown"), operation: Some("Update"), subresource: None, time: Some(Time(2023-08-01T11:01:39Z)) }, ManagedFieldsEntry { api_version: Some("brupop.bottlerocket.aws/v2"), fields_type: Some("FieldsV1"), fields_v1: Some(FieldsV1(Object {"f:status": Object {".": Object {}, "f:crash_count": Object {}, "f:current_state": Object {}, "f:current_version": Object {}, "f:target_version": Object {}}})), manager: Some("unknown"), operation: Some("Update"), subresource: Some("status"), time: Some(Time(2023-08-01T11:01:59Z)) }]), name: Some("brs-ip-10-100-2-30.eu-central-1.compute.internal"), namespace: Some("brupop-bottlerocket-aws"), owner_references: Some([OwnerReference { api_version: "v1", block_owner_deletion: None, controller: None, kind: "Node", name: "ip-10-100-2-30.eu-central-1.compute.internal", uid: "ad5d1972-7496-49dd-b461-7514804d38f2" }]), resource_version: Some("328098224"), self_link: None, uid: Some("f03bc730-576f-4149-bcce-b1ef28ec2933") }, spec: BottlerocketShadowSpec { state: Idle, state_transition_timestamp: None, version: None }, status: Some(BottlerocketShadowStatus { current_version: "1.14.3", target_version: "1.14.3", current_state: Idle, crash_count: 0, state_transition_failure_timestamp: None }) }, state: Idle, shadow_error_info: ShadowErrorInfo { crash_count: 0, state_transition_failure_timestamp: None }
    in agent::agentclient::run
```
</details>

The line `The lock for the update API is held by another process` appears in all agents' logs and it's unclear what process is being referred to.

<details>
<summary>BRS object</summary>

```
apiVersion: brupop.bottlerocket.aws/v2
kind: BottlerocketShadow
metadata:
  creationTimestamp: "2023-08-01T11:01:39Z"
  generation: 6
  name: brs-ip-1-2-3-4.eu-central-1.compute.internal
  namespace: brupop-bottlerocket-aws
  ownerReferences:
  - apiVersion: v1
    kind: Node
    name: ip-1-2-3-4.eu-central-1.compute.internal
    uid: 639a40e7-d71a-4ad8-ae8c-ecc75d017e24
  resourceVersion: "328098224"
  uid: 2e518bee-89b9-447b-9582-c8a779e74038
spec:
  state: Idle
status:
  crash_count: 0
  current_state: Idle
  current_version: 1.14.3
  target_version: 1.14.3
```

</details>

The shadow claims that there's nothing to do, as does `apiclient update check`:
<details>
<summary>output</summary>

```
09:53:18 [INFO] Refreshing updates...
{
  "active_partition": {
    "image": {
      "arch": "x86_64",
      "variant": "aws-k8s-1.24",
      "version": "1.14.3"
    },
    "next_to_boot": true
  },
  "available_updates": [
    "1.14.3",
    "1.14.2",
    "1.14.1",
    "1.14.0",
    "1.13.5",
    "1.13.4",
    "1.13.3",
    "1.13.2",
    "1.13.1",
    "1.13.0",
    "1.12.0",
    "1.11.1",
    "1.11.0",
    "1.10.1",
    "1.10.0"
  ],
  "chosen_update": null,
  "most_recent_command": {
    "cmd_status": "Success",
    "cmd_type": "refresh",
    "exit_status": 0,
    "stderr": "",
    "timestamp": "2023-09-05T09:53:18.998699935Z"
  },
  "staging_partition": null,
  "update_state": "Idle"
}
```
</details>

However, the nodes' AMIs seen in AWS console or in node's manifest do not correspond to that version. I didn't yet change my node group to reference the SSM parameter, but I'd still expect the node to have the correct AMI for 1.14.3, yet it shows one for 1.14.2.

Now the question is, is this intended behavior or am I missing something?

**Comment by cbgbt** [comment]
Hello. Thanks for providing so much detail here.
> The lock for the update API is held by another process

This isn't a problem, but I concede that it reads like one. This should probably be emitted at `DEBUG` level. Sorry that it caused some confusion.

The Bottlerocket update API has an exclusive lock which can sometimes be held by other processes, or be slow-to-drop from previous operations that Brupop performs.

> The shadow claims that there's nothing to do, as does `apiclient update check` ... However, the nodes' AMIs seen in AWS console or in node's manifest do not correspond to that version.

Bottlerocket's update system is in-place. The AMI has a disk partition set aside to which it downloads a new immutable filesystem, and then it reboots into it ([relevant docs](https://github.com/bottlerocket-os/bottlerocket#updates)). In your case, your instances *are* running the latest Bottlerocket, even if they were originally launched on an older AMI ID and still refer to that ID. Indeed, new instances will still launch with the outdated image and then be updated by Brupop. Unfortunately, AMI ID selection is handled at a layer of abstraction outside of Brupop's control -- Brupop and Bottlerocket are designed to operate within arbitrary kubernetes clusters, but the AMI ID is at the cloud provider layer.

We had a feature request (https://github.com/bottlerocket-os/bottlerocket-update-operator/issues/45) to support updating ASGs in the operator after the hosts themselves are updated. This is solved by ASGs adding [the ability to resolve SSM parameters for AMI IDs](https://docs.aws.amazon.com/autoscaling/ec2/userguide/using-systems-manager-parameters.html) instead of referring to a static AMI ID. Unfortunately [this isn't yet supported by `eksctl`](https://github.com/eksctl-io/eksctl/issues/6174). (EDIT: I realized after re-reading your message that you are already aware of this. Hope my message clarifies things)


I'll keep this issue open while I track down making that log message less concerning. Happy to answer any more questions.

**Comment by cbgbt** [comment]
#539 should clarify the logs, but I'll leave this open for a bit in case you have any other questions.

**Comment by jRilkef** [comment]
Hey @cbgbt , thanks a ton for such detailed reply! It really helped.

I don't use `eksctl`, instead my infrastructure is managed by Terraform, including node groups. However, up to this point I've been using managed node groups for historical reasons. To take advantage of the ability to reference SSM parameters, do I have to switch to self-managed node groups? I imagine if I do, then when an updated AMI becomes available
- Brupop notices an update and applies it => "old" nodes are running the new image
- if scale out event happens it'll have the new AMI as well => Brupop won't have to update it until an even newer AMI is released

Is that correct?

**Comment by cbgbt** [comment]
I was under the impression that you would have to switch to self-managed node groups, but I found [this](https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-custom-ami) in the EKS docs, which implies to me that it should work to use a custom launch template with an SSM parameter? I haven't tested through.

In either the above case or the self-managed case that you mention, I believe that you'd get the versioning behavior that you mention.
