### ISSUE TITLE
Clarify updater-interface-version

### ISSUE THREAD

**Issue by bgdnlp** [bottlerocket-os/bottlerocket-update-operator#54]
This is more of a documentation request. Would it be possible to clarify a few things regarding `updater-interface-version` in the README? It took some digging for me to find out. Like:
1. 1.0.0 vs 2.0.0 (updog vs API). It's unclear what is version 1 and what is v2 and why they are versioned. Simply using "updog" vs "api" instead would help, I see there was a comment about it in the pull request.
2. When should one use Updog instead of API, and is there any reason to use "1.0.0" on Bottlerocket v1.0+?
3. In cases where API si fine, should the `update-operator-agent-updog` DaemonSet be removed from the K8s manifest? 600 MiB is a lot of memory for a container that runs on every node. And the manifest has two of those. That's 1.2 GiB, which is huge. See #47.

**Comment by etungsten** [comment]
Hi @bgdnlp 

1. The platform version lets us differentiate deployments that might be specific to certain host versions. The only use right now is to differentiate between hosts that support the update api and hosts that do not. If the host API surface changes in a incompatible way, we would need to introduce new platform versions.
2. The updog deployment should only be used with bottlerocket hosts that do not support the update API (any Bottlerocket version < 0.4.1). This is definitely a documentation issue we need to address. The default recommended updater-interface-version node label to apply should be 2.0.0
3. The updog agent pod should not run if the updater-interface-version is set to 2.0.0. Conversely the update api agent won’t run if the updater-interface-version isn’t set to 2.0.0. We’ll adjust the memory reserved for the update-api agent DaemonSet to something more befitting.
