### ISSUE TITLE
Question regarding Brupop's Support Policy

### ISSUE THREAD

**Issue by mooneeb** [bottlerocket-os/bottlerocket-update-operator#548]
**Image I'm using:**
N/A

**Issue or Feature Request:**
This isn't an issue or a feature request, rather a question:

What is the support policy for Brupop in terms of which versions are supported at a given time and which version(s) are recommended to be installed on a prod cluster? I went through the documentation but could not find this information.

I would be grateful if someone could please guide me on this ^_^

**Comment by cbgbt** [comment]
Hey, thanks for raising this question. We should probably look at providing guidance around this in the README.

Brupop follows semver, so changes introduced in minor versions will not introduce breaking or backwards-incompatible changes. Only the latest minor version receives patches for security issues.

Given this policy, I'd recommend always using the latest version of Brupop available.

**Comment by mooneeb** [comment]
@cbgbt Thank you! This is very helpful 😃 If I may, I'd just like to reiterate your guidance via an example so that I know I've understood it correctly.

> Since `v1.3.0` is the latest brupop release, `v1.3` is considered supported and `v1.3.0` (since it is the latest released version) is the one recommended to be installed (if `v1.3.1` is released, then `v1.3.1` will be recommended)

Please let me know if my understanding is correct.

And I agree having the support policy be a part of the README will be very valuable to other users who might be after the same information :) I'll be very happy to make a PR if you'd like me to.

**Comment by stmcginnis** [comment]
That's right @mooneeb!

> I'll be very happy to make a PR if you'd like me to.

That would be great! If you have a chance to do that, @cbgbt and I will watch out for the PR and make sure it gets reviewed quickly. Thank you!

**Comment by mooneeb** [comment]
@stmcginnis @cbgbt I've created the PR: https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/550 :)
