### ISSUE TITLE
Increase observability

### ISSUE THREAD

**Issue by swade1987** [bottlerocket-os/bottlerocket-update-operator#57]
**Issue or Feature Request:**

I would love to have more observability into what the update operator is doing within our clusters.

The upgrade from 1.0.5 to 1.0.6 happened over the past week and I had little to no idea it was taking place.

Ideally the exposure of some prometheus metrics that provide the following information

- The agents current status (e.g. no updates pending, update pending, update complete)
- The status of the wave execution (number of nodes completed, number remaining)

From this the creation of a community owned Grafana dashboard visualising this information.

**Comment by jhaynes** [comment]
Hi @swade1987 I'm glad to hear the operator is working well for you. When we designed Bottlerocket and the update operator, this invisibility was something we were striving for. However, as you point out, some data about progress and status, even when things are going well, is often very helpful. We'll look at what is involved in Prometheus metrics from the updater soon. If you have other thoughts on specific metrics, let us know!

**Comment by swade1987** [comment]
Any update on this as we've stalled using the operator until we can get better visibility into what's going on.

**Comment by jahkeup** [comment]
As a note: #17 has some observability/visibility thoughts written down that might play into a solution for this issue.

**Comment by cbgbt** [comment]
Hello. We have recently released version [0.2.0](https://github.com/bottlerocket-os/bottlerocket-update-operator/releases/tag/v0.2.0) of the update operator, which provides mechanisms for observing current state via `kubectl`, as well as historic state using Prometheus metrics endpoints. We'd really appreciate if you tried out the new version and let us know what you think!

I'll close this issue, but if you have questions or feedback, feel free to comment or cut another issue. Thanks!
