### ISSUE TITLE
updater fails to upgrade to 1.0.8

### ISSUE THREAD

**Issue by snstanton** [bottlerocket-os/bottlerocket-update-operator#59]
I'm having trouble with the update operator not updating my nodes to 1.0.8.  It's not noticing there is a new image to update.
I'm currently running: `ami-05001739c6b8574a6: amazon/bottlerocket-aws-k8s-1.19-x86_64-v1.0.7-099d3398`
but I can see `ami-04269f2e9be10beeb: amazon/bottlerocket-aws-k8s-1.19-x86_64-v1.0.8-fee7e752` is available

all the nodes are showing:

    "bottlerocket.aws/update-available": "false",
    "bottlerocket.aws/updater-interface-version": "2.0.0"

neither the controller nor the agents are showing any errors.
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by snstanton** [comment]
I think this is just an issue of different nodes being in different upgrade waves.

**Comment by tjkirch** [comment]
Glad you found the answer!  I'm going to post what I had typed out anyway, in case someone else finds this issue for similar reasons :)

---

Hi @snstanton - the v1.0.8 update is currently rolling out and isn't available to all hosts yet.  (That's unrelated to the bottlerocket-update-operator.)

We base our update schedule on "waves" that you can read a bit more about [here](https://github.com/bottlerocket-os/bottlerocket/tree/develop/sources/updater#update-wave) and [here](https://github.com/bottlerocket-os/bottlerocket/tree/develop/sources/updater/waves#update-waves).  Basically, each host generates a "seed" number between 0 and 2048 that determines where in the wave structure it falls, with 0 being immediate updates and 2048 being last.  This process usually takes about a week after a release, unless it was an urgent release for security reasons.  This helps us control update velocity and detect failures before they impact a large number of users.

You can change `settings.updates.seed` if you want to fall in a certain place in the rollout, or set `settings.updates.ignore-waves` if you always want immediate updates.  You can see your seed on a given host with `apiclient -u /settings?keys=settings.updates.seed`.
