### ISSUE TITLE
Drop updog integration

### ISSUE THREAD

**Issue by jahkeup** [bottlerocket-os/bottlerocket-update-operator#60]
**Image I'm using:**

n/a

**Issue or Feature Request:**

The [`updog` platform integration](https://github.com/bottlerocket-os/bottlerocket-update-operator/tree/4f24dc29fb654d116df58c3480b8b5c62727c861/pkg/platform/updog) needs to be deprecated and removed entirely. Nodes now should (and must) use the [`update-api`](https://github.com/bottlerocket-os/bottlerocket-update-operator/tree/4f24dc29fb654d116df58c3480b8b5c62727c861/pkg/platform/api) to perform updates. Bottlerocket's SELinux policies prevent `updog` from functioning and is/was only suitable for use with images released during public preview.

- [ ] log any remaining use of deprecated `updog` integration
- [ ] remove `updog` integration code (in a later release)

**Related**

#47

**Comment by cbgbt** [comment]
We ultimately dropped updog support in the latest Update Operator release, [0.2.0](https://github.com/bottlerocket-os/bottlerocket-update-operator/releases/tag/v0.2.0). This should be okay to close!
