### ISSUE TITLE
Enable podLabels to create identifiers for Kubecost

### ISSUE THREAD

**Issue by danielvvoros** [bottlerocket-os/bottlerocket-update-operator#616]
**Image I'm using:** v1.3.0.
**Issue or Feature Request:** Feature Request.

Hi, folks! My suggestion is that we add the `podLabels` identifier to enable Kubecost's identification function and also other use cases.

**Comment by vyaghras** [comment]
@danielvincenzi  Thanks for raising the issue and opening the [PR](https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/617). We will look in to the PR soon.

**Comment by ytsssun** [comment]
https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/617 is merged.
