### ISSUE TITLE
Add How to build update operator image steps in docs

### ISSUE THREAD

**Issue by srgothi92** [bottlerocket-os/bottlerocket-update-operator#66]
**Image I'm using:**
N/A

**Issue or Feature Request:**
Documentation

**Comment by cbgbt** [comment]
[Instructions have been added](https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/08f5a15ba6ab513c0f4d58b7313cc14fce196397/README.md#building-and-deploying-a-development-image) to the README pertaining to building the update operator image.
