### ISSUE TITLE
Change `context.TODO()` with better context handling 

### ISSUE THREAD

**Issue by srgothi92** [bottlerocket-os/bottlerocket-update-operator#71]
**Image I'm using:**
N/A

**Issue or Feature Request:**
Issue

**Description** 

Kubernetes go client library was updated as part of [PR-70](https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/70), but the newer version requires context in lots of API's. The context was difficult to determine so It was set as `context.TODO()` as part of [PR-70](https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/70). We should change it to more meaningful context.

**Comment by cbgbt** [comment]
This shouldn't be an issue in the latest Update Operator release, [0.2.0](https://github.com/bottlerocket-os/bottlerocket-update-operator/releases/tag/v0.2.0), which has changed implementations to use [kube-rs](https://github.com/kube-rs/kube-rs)
